# Generated by Django 5.1 on 2024-08-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0003_product_is_liked_alter_attributevalue_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='texnomart.product'),
        ),
    ]
