# Generated by Django 5.1 on 2024-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0005_remove_product_is_liked_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
