# Generated by Django 5.1 on 2024-08-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0006_product_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
